title: Dynamic Data Visualization Workshop (2021)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
google_analytics: UA-219202870-2
locale: "en"
markdown: kramdown
