title: Dynamic Data Visualization Workshop (2021)
project_name: Dynamic Data Visualization Workshop (2021)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
is_project_page: true
show_downloads: true
google_analytics: UA-219202870-2
